### ISSUE TITLE
asyncio.exceptions.IncompleteReadError after every request

### ISSUE THREAD

**Issue by lapcchan** [matteobertozzi/asyncio-simple-http-server#1]
getting the following warning after every request, besides the warning log itself everything works fine.

2024-10-02 10:45:14,122 WARNING asyncio_simple_http_server server.py _handle_client():219 - got a failure <class 'asyncio.exceptions.IncompleteReadError'>. disconnecting the client

**Comment by matteobertozzi** [comment]
Hi, I've added a http_server.trace_client_disconnection flag to enable/disable the client disconnection log https://github.com/matteobertozzi/asyncio-simple-http-server/commit/43a114caa86283ff4aef36f269e7e849282a31fd

```python
http_server = HttpServer()
http_server.trace_client_disconnection = False
...
```
